name: FlowTurbo
channels:
  - pytorch
  - nvidia
dependencies:
  - python >= 3.9
  - pytorch >= 2.0.0
  - torchvision
  - pytorch-cuda >=11.7
  - pip
  - pip:
    - timm
    - diffusers
    - accelerate
